# This script deploys the Creto Blog to the gh-pages branch
name: CI

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    
    - run: npm install

    # Run our deployment command
    - name: Deploying the static website to gh-pages
      run: gulp buildPush
